name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
- name: ftp-action
  uses: sebastianpopp/ftp-action@v2.0.0
  with:
    host: ftp.ciaodafabio.jp
    user: fabiojp@ciaodafabio.jp
    password: gandalf715
    remoteDir: /public_html/